import React, { createContext, useContext, useState, useEffect } from 'react';
import CITY_CONFIG from '../config/cityConfig';

const LanguageContext = createContext();

const translations = {
  en: {
    adminPortal: 'Admin Portal',
    navigationMenu: 'Navigation Menu',
    systemOverview: 'System Overview',
    totalUsersAdmin: 'Total Users',
    totalHousesAdmin: 'Total Houses',
    rentalRequestsAdmin: 'Rental Requests',
    activeRentalsAdmin: 'Active Rentals',
    platformAnalytics: 'Platform Analytics',
    daily: 'Daily',
    monthly: 'Monthly',
    yearly: 'Yearly',
    housesPostedOverTime: 'Houses Posted Over Time',
    noConversationsFound: 'No conversations found',
    selectAChatConversation: 'Select a Chat Conversation',
    houseManagement: 'House Management',
    categoriesManagement: 'Categories Management',
    listingGuide: 'Listing Guide',
    noPropertiesListed: 'No properties listed',
    addYourFirstProperty: 'Add Your First Property',
    myHouseSeekingAds: 'My House Seeking Ads',
    preferredLocation: 'Preferred Location in Injibara',
    postRequestAd: 'Post Request Ad',
    recipient: 'Recipient',
    status: 'Status',
    totalListings: 'Total Listings',
    allPropertiesPosted: 'All properties posted',
    activeListingsStatus: 'Active Listings',
    currentlyAvailable: 'Currently available for rent',
    successfullyRented: 'Successfully Rented',
    totalOccupied: 'Total properties occupied',
    posted: 'Posted',
    rentedStatus: 'Rented',
    propertyConversion: 'Property Conversion',
    relativeComparison: 'Relative comparison of listing status',
    performanceInsight: 'Performance Insight',
    yourSavedProperties: 'Your Saved Properties',
    // Nav
    home: 'Home',
    houses: 'Houses',
    categories: 'Categories',
    mapView: 'Map View',
    about: 'About',
    contact: 'Contact',
    messages: 'Messages',
    dashboard: 'Dashboard',
    signIn: 'Sign In',
    register: 'Register',
    signOut: 'Sign Out',
    today: 'Today',
    loginToMessage: 'Log In to Message',
    loginToMessageDesc: 'Please log in to your account to view and send direct rental messages between brokers and tenants.',
    messagesSubtitle: `Communicate securely regarding house rentals, viewings, and pricing across ${CITY_CONFIG.cityNameEn} City Kebeles.`,
    brandSub: CITY_CONFIG.brandSubEn,
    amharaHouse: CITY_CONFIG.brandNameEn,
    langName: 'English',
    switchLang: 'አማርኛ',
    // Home / General
    welcomeTitle: CITY_CONFIG.heroTitleEn,
    searchPlaceholder: CITY_CONFIG.searchPlaceholderEn,
    searchBtn: 'Search Houses',
    requestRental: 'Request Rental',
    availableHouses: 'Available Houses',
    viewDetails: 'View Details',
    contactOwner: 'Contact Landlord',
    featuredHouses: 'Featured Houses',
    allCategories: 'All Categories',
    price: 'Price',
    perMonth: 'ETB/month',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    roomsLabel: 'Rooms',
    bathsLabel: 'Baths',
    area: 'Area',
    sqm: 'm²',
    sqmFull: 'Square Meters',
    typeLabel: 'Type',
    location: 'Location',
    saveProperty: 'Save',
    saved: 'Saved',
    available: 'Available for Rent',
    rented: 'Rented',
    vipFeatured: 'VIP Featured',
    chatLandlord: 'Chat Landlord',
    contactBroker: 'Broker',
    requestBtn: 'Request',
    showingProperties: `Showing rental properties in ${CITY_CONFIG.cityNameEn}`,
    sortBy: 'Sort By',
    featuredFirst: 'Featured First',
    newestFirst: 'Newest Listed',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    noPropertiesFound: 'No properties found',
    noPropertiesMsg: `We couldn't find any house rentals matching your selected criteria in ${CITY_CONFIG.cityNameEn}.`,
    clearFilters: 'Clear All Filters',
    // Dashboard / User Portal
    properties: 'My Properties',
    favs: 'Favorites',
    rentRequests: 'Rental Requests',
    seekingAds: 'Tenant Ads',
    savedAlerts: 'Saved Alerts',
    payments: 'Payments',
    profile: 'Profile',
    analytics: 'Analytics',
    allUsers: 'All Users',
    activeListings: 'Active Listings',
    rentedListings: 'Rented Listings',
    postedVsRented: 'Posted vs. Rented properties over time',
    performanceDashboard: 'Property Analytics Dashboard',
    // Forms
    addProperty: 'Add New Property',
    editProperty: 'Edit Property',
    titleLabel: 'Title',
    descLabel: 'Description',
    rooms: 'Rooms',
    baths: 'Baths',
    sqmLabel: 'Square Meters',
    region: 'Region',
    city: 'City',
    subCity: 'Sub-city',
    address: 'Address',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    // Alerts
    minPrice: 'Min Budget',
    maxPrice: 'Max Budget',
    locationKeyword: 'Location Keyword',
    minRooms: 'Min Rooms',
    notificationEmail: 'Notification Email',
    createAlert: 'Create Search Alert',
    testAlert: 'Send Test Alert',
    emailLogs: 'Email Notification Logs',
    preview: 'Preview',
    // Categories / Types
    residential: 'Residential House',
    villa: 'Villa',
    apartment: 'Apartment',
    commercial: 'Commercial / Shop',
    condo: 'Condominium',
    studio: 'Studio / Annex',
    office: 'Office Space',
    warehouse: 'Warehouse',
    land: 'Land / Plot',
    // About Page
    aboutHeroTag: 'Injibara City Real Estate & House Brokerage',
    aboutHeroTitle: 'Redefining House Rentals Across Injibara City',
    aboutHeroSubtitle: 'Injibara Homes bridges the gap between house seekers and property owners across Injibara City Kebeles, University area, and Bus Station.',
    exploreHouses: 'Explore Houses',
    browseCategories: 'Browse Categories',
    ourMission: 'Our Mission',
    missionText: 'To simplify and revolutionize the Ethiopian housing market by providing a digital-first platform where searching, listing, and requesting quality home rentals is transparent, fair, and accessible to everyone.',
    ourVision: 'Our Vision',
    visionText: 'To become East Africa\'s most trusted real estate ecosystem, empowering thousands of tenants and property managers with modern software, verified analytics, and direct communication channels.',
    coreValues: 'Core Values',
    valuesText: 'Integrity, speed, and community empowerment. We believe every tenant deserves a comfortable home and every landlord deserves reliable management without exorbitant broker fees.',
    verifiedListings: '100% Verified ETB Listings',
    nationwideCoverage: 'Nationwide Ethiopian Coverage',
    zeroFees: 'Zero Hidden Broker Fees',
    tailoredExp: 'Tailored Experience',
    builtForBoth: 'Built for Tenants and Landlords Alike',
    streamlineDesc: 'Switch views below to see how EthioHomes streamlines the journey for both sides of the rental equation.',
    forTenants: 'For House Seekers (Tenants)',
    forLandlords: 'For Property Owners (Landlords)',
    kebeleFiltering: 'Smart Kebele Filtering',
    kebeleFilteringDesc: 'Search by Kebele (01, 02, 03), Injibara University Area, or Bus Station Area to locate homes in your preferred neighborhood.',
    oneClickRequest: '1-Click Rental Requests',
    oneClickRequestDesc: 'Express interest with a single click. Landlords receive immediate notifications in their dashboard for rapid evaluation.',
    liveUpdates: 'Live Status Updates',
    liveUpdatesDesc: 'Monitor request updates in real time via your personal Tenant Dashboard—from pending to approved leases.',
    freeListings: 'Free Property Listings',
    freeListingsDesc: 'Add unlimited houses, apartments, and studios with high-res photos, pricing in ETB, and room details.',
    reviewApplicants: 'Review Applicant Profiles',
    reviewApplicantsDesc: 'Inspect incoming tenant requests, verify applicant phone numbers and emails, and choose who moves in.',
    dashboardMgmt: 'Dashboard Management',
    dashboardMgmtDesc: 'Update house status (Available or Rented), modify prices, and manage active leases seamlessly in one place.',
    ourFootprint: 'Our Footprint Across Ethiopia',
    footprintDesc: 'Connecting luxury apartments and family villas in key growth cities.',
    propertiesListed: 'Properties Listed',
    majorCities: 'Major Ethiopian Cities',
    verifiedUsers: 'Verified Users',
    tenantSatisfaction: 'Tenant Satisfaction',
    faqTitle: 'Frequently Asked Questions',
    gotQuestions: 'Got Questions? We Have Answers',
    navigatingDesc: 'Everything you need to know about navigating EthioHomes.',
    readyToFind: 'Ready to find your dream house?',
    browseDesc: 'Browse hundreds of verified apartments, villas, and commercial spaces across Ethiopia today.',
    browseNow: 'Browse Houses Now',
    // Rental Request Modal
    bookingRequest: 'Booking Request',
    reviews: 'Reviews',
    moveInDate: 'Move-in Date',
    noteToOwner: 'Note to Owner',
    sendRequest: 'Send Rental Request',
    propertyRented: 'Property Rented',
    alreadyRentedMsg: 'This house is already rented! A property cannot be rented to multiple customers at the same time.',
    bookingSuccess: 'Rental Request Sent!',
    bookingSuccessMsg: 'Your booking request has been successfully delivered to the property owner.',
    digitalContract: 'Digital Rental Contract PDF',
    prepareContract: 'Need a legal contract?',
    // Navbar Extras
    dateTime: 'Date & Time',
    currentTime: 'Current Time',
    notifs: 'Notifications',
    markAllRead: 'Mark all as read',
    noNotifs: 'No notifications yet',
    watchVideo: 'Watch Video',
    allHouses: 'All Houses',
    filterByCity: 'Filter by City',
    allCities: 'All Cities',
    filterByType: 'Filter by Type',
    allTypes: 'All Types',
    priceRange: 'Price Range (ETB)',
    searchHouses: 'Search houses...',
    noHousesFound: 'No houses found matching your criteria.',
    testimonialTitle: 'Trusted by Thousands Across Injibara City',
    testimonialSubtitle: 'Read what tenants, home seekers, and property owners say about finding and renting verified houses.',
    customerExperience: 'Customer Experiences',
    rentReminders: 'Rent Reminders',
    contracts: 'Contracts',
    requestPropertyPost: 'Request to Post Property',
    close: 'Close',
    ownerSelectDesc: 'The property will be assigned to the selected owner; tenants will chat directly with this person.',
    propertyCategories: 'Property Categories',
    categoriesInInjibara: 'Property Categories in Injibara City',
    categoriesDesc: 'Explore residential houses, commercial shops, restaurant spaces, and clinic venues across Injibara City.',
    contactUs: 'Contact Us',
    getInTouch: 'Get in Touch',
    contactDesc: 'Looking to rent or list a property? Call us or send a direct message.',
    contactDetails: 'Contact Details',
    contactDetailsDesc: 'Contact our office directly for prompt house viewings, tenant matchmaking, and property listings.',
    phone: 'Phone',
    email: 'Email',
    officeLocation: 'Office Location',
    officeLocationValue: 'Injibara, Kebele 01 (Near CBE Branch), Awi Zone',
    sendMessage: 'Send Us a Message',
    yourName: 'Your Name',
    enterYourName: 'Enter your full name',
    yourEmail: 'Your Email',
    subject: 'Subject',
    propertySubject: 'Property request subject',
    message: 'Message',
    writeMessage: 'Write your detailed message...',
    messageSentSuccess: 'Thank you! Message sent successfully.',
    addPropertyTitle: 'Add Property Listing',
    addPropertySubtitle: 'Fill in the details to promote your house to potential tenants.',
    ownerSelection: 'Landlord Selection',
    ownerSelectPlaceholder: '-- Select Owner --',
    propertyTitle: 'Property Title',
    propertyTitlePlaceholder: 'e.g. 2 Bedroom house in Kebele 01',
    regionArea: 'Region / Area',
    cityZone: 'City / Zone',
    subCityWereda: 'Wereda / Sub-City',
    rentPriceLabel: 'Monthly Rent (ETB)',
    pricePlaceholder: 'e.g. 8500',
    roomsCount: 'Number of Rooms',
    bathroomsCount: 'Number of Bathrooms',
    squareMeterLabel: 'Square Meters',
    addressLabel: 'Specific Address',
    addressPlaceholder: 'e.g. Behind Agni Hospital',
    propertyImages: 'Property Images',
    propertyImagesDesc: 'Adding 3-5 high-quality photos helps tenants see the property better.',
    propertyVideo: 'Video Walkthrough',
    propertyVideoDesc: 'Add a short video walkthrough to better showcase the house.',
    submitListing: 'Submit Listing',
    createAccount: 'Create Account',
    joinNetwork: "Join Ethiopia's premier real estate & house rental network",
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    iamA: 'I am a...',
    houseSeeker: 'Tenant (House Seeker)',
    propertyOwner: 'Landlord (Property Owner)',
    registerBtn: 'Register Now',
    alreadyHaveAccount: 'Already have an account?',
    loginLink: 'Log In',
    signInTitle: 'Welcome Back',
    signInSubtitle: 'Access your tenant messages, saved favorites, or landlord house listings.',
    dontHaveAccount: "Don't have an account?",
    registerLink: 'Register Now',
    loggingIn: 'Logging In...',
    online: 'Online',
    cityTown: 'City / Town',
    selectCity: 'Select City',
    kebeleOptional: 'Sub-City / Kebele (Optional)',
    creatingAccount: 'Creating Account...',
    completeRegistration: 'Complete Account Registration',
    virtualTour: '360° Virtual House Tour',
    virtualTourSubtitle: 'Watch full walkthrough video of this property',
    openLink: 'Open Link',
    dateListed: 'Date Listed',
    propertyAmenities: 'Property Highlights & Amenities',
    waterReservoir: 'Water Reservoir Tank',
    electricMeter: 'Separate Electric Meter',
    parkingSpace: 'Parking Space',
    secureCompound: 'Secure Fenced Compound',
    nearMainRoad: 'Near Main Asphalt Road',
    readyMoveIn: 'Ready for Immediate Move-in',
    propertyDescription: 'Property Description',
    defaultDescription: 'This well-maintained property is located in a prime area of Injibara City, offering modern facilities, continuous water supply, and easy access to local amenities.',
    instantContact: 'Instant Contact Options',
    callPhone: 'Call Phone',
    verifiedBroker: 'Verified Broker & Landlord',
    findPropertyTitle: 'Find Your Property in Injibara City',
    findPropertyDesc: 'Verified residential houses and commercial spaces across Injibara City Kebeles and University area.',
    filters: 'Filters',
    clear: 'Clear',
    areaKebele: 'Injibara Area / Kebele',
    allAreas: 'All Injibara Areas',
    propertyType: 'Property Type',
    residentialHouse: 'Residential House',
    commercialShop: 'Commercial Shop',
    hotelShiro: 'Hotel & Restaurant / Shiro',
    electronicsPhoto: 'Electronics & Photo Studio',
    pharmacyClinic: 'Pharmacy & Clinic',
    otherCommercial: 'Other Commercial Spaces',
    applyFilters: 'Apply Filters',
    liveTenantRequests: 'Live Tenant Requests',
    tenantSeekingTitle: 'Browse Tenant Requests',
    tenantSeekingSubtitle: 'Landlords & Brokers: See what potential tenants are looking for and contact them directly!',
    postSeekingRequest: 'Post Your House Requirement',
    noSeekingRequests: 'No pending requests yet',
    noSeekingRequestsDesc: 'Register your house requirements and let landlords find you!',
    postFirstRequest: 'Post First Request',
    seeker: 'Tenant (Seeker)',
    postedOn: 'Posted on',
    call: 'Call',
    houseType: 'House Type',
    notSpecified: 'Not Specified',
    budget: 'Budget',
    contactLandlordSystem: 'Contact Landlord via System',
    selectFromList: 'Select from list',
    typeCustom: 'Type Custom',
    customHouseTypePlaceholder: 'Type the house type you need (e.g. Shop, Warehouse)',
    maxBudget: 'Max Budget',
    budgetPlaceholder: 'e.g. 15000',
    locationPlaceholderSeeking: 'e.g. Injibara - Kebele 01 (Near Hospital)',
    room: 'Room',
    additionalDetails: 'Additional Details',
    seekingDescriptionPlaceholder: 'e.g. Near main road, has water tank, quiet area...',
    registering: 'Registering...',
    submitSeekingRequest: 'Submit Seeking Request',
    registeredSuccessfully: 'Registered Successfully!',
    seekingRequestSuccessMsg: 'Your request has been posted and is now featured on the homepage slider.',
    viewSlider: 'View Slider',
    verifiedPlatform: 'Verified Platform',
    verifiedProperty: 'Verified Property',
    directLandlordContact: 'Direct Landlord Contact',
    shareProperty: 'Share Property',
    copied: 'Copied!',
    videoPlaybackError: 'Your browser does not support video playback.',
    defaultLocation: 'Injibara, Ethiopia',
    landlordLabel: 'Landlord',
    monthlyRent: 'Monthly Rent',
    directMessaging: 'Direct Messaging',
    smartPropertyMap: 'Smart Property Map',
    houseRentalBooking: 'House Rental Booking',
    allRightsReserved: 'All rights reserved.',
    footerDescription: 'Find verified residential houses and commercial spaces in Injibara City.',
    ethiopia: 'Ethiopia',
    inAppDirectMessaging: 'In-App Direct Messaging',
    exploreProperties: 'Explore Properties',
    searchMessages: 'Search messages or contacts...',
    contactLandlords: 'Contact Landlords',
    sendMessageAction: 'Send Message',
    startChatting: 'Start chatting with a landlord directly from property details!',
    onlineCaps: 'ONLINE',
    onlineStatus: 'Online',
    offlineStatus: 'Offline',
    viewDetailsAction: 'View Details',
    testingModeMsg: 'This is your own property/account (Testing Mode). You can send test messages below!',
    beginningOfConversation: 'This is the beginning of your direct conversation.',
    askQuestions: 'Ask questions about rental conditions, prices, or viewing appointments!',
    sentStatus: 'Sent',
    writeMessageTo: 'Write a message to',
    sendAction: 'Send',
    selectConversation: 'Select a conversation',
    chooseToStartChatting: 'Choose a landlord or tenant from the left sidebar to start chatting in real time.',
    interactiveMap: 'Interactive Map',
    mapDesc: 'Easily explore properties on a visual map, or use AI search to auto-filter by location, category, and price.',
    featuredPropertiesText: 'Featured Properties',
    loadingProperties: 'Loading available properties...',
    exploreAvailable: 'Explore available',
    propertiesInInjibara: 'properties in Injibara and surrounding areas',
    viewAll: 'View All',
    calendarInfo: 'Choose in Ethiopian Calendar (EC) or standard Gregorian date.',
  },
  am: {
    adminPortal: 'አስተዳዳሪ',
    navigationMenu: 'ዋና ማውጫ',
    systemOverview: 'ስርዓት አጠቃላይ እይታ',
    totalUsersAdmin: 'አጠቃላይ ተጠቃሚዎች',
    totalHousesAdmin: 'አጠቃላይ ቤቶች',
    rentalRequestsAdmin: 'የኪራይ ጥያቄዎች',
    activeRentalsAdmin: 'በአሁኑ ጊዜ ያሉ ኪራዮች',
    platformAnalytics: 'የመድረክ መረጃዎች',
    daily: 'በቀን',
    monthly: 'በወር',
    yearly: 'በአመት',
    housesPostedOverTime: 'በየጊዜው የተለጠፉ ቤቶች',
    noConversationsFound: 'ምንም መልዕክት አልተገኘም',
    selectAChatConversation: 'የመልዕክት ልውውጥ ይምረጡ',
    houseManagement: 'የቤቶች አስተዳደር',
    categoriesManagement: 'የምድቦች አስተዳደር',
    listingGuide: 'የምዝገባ መመሪያ',
    noPropertiesListed: 'ምንም የተመዘገበ ቤት የለም',
    addYourFirstProperty: 'የመጀመሪያ ቤቶን ያስመዝግቡ',
    myHouseSeekingAds: 'የእኔ የቤት ፈላጊ ማስታወቂያዎች',
    preferredLocation: 'የሚፈልጉት ቦታ (በእንጅባራ)',
    postRequestAd: 'ማስታወቂያ ለጥፍ',
    recipient: 'ተቀባይ',
    status: 'ሁኔታ',
    totalListings: 'አጠቃላይ ቤቶች',
    allPropertiesPosted: 'የተመዘገቡት ሁሉም ቤቶች',
    activeListingsStatus: 'በአሁኑ ጊዜ ያሉ ቤቶች',
    currentlyAvailable: 'አሁን ለኪራይ የቀረቡ',
    successfullyRented: 'በተሳካ ሁኔታ የተከራዩ',
    totalOccupied: 'የተያዙ ቤቶች ብዛት',
    posted: 'የተመዘገቡ',
    rentedStatus: 'የተከራዩ',
    propertyConversion: 'የቤቶች ሁኔታ',
    relativeComparison: 'የቤቶች ንጽጽር',
    performanceInsight: 'የስራ አፈጻጸም',
    yourSavedProperties: 'ያጠራቀሟቸው ቤቶች',
    findPropertyTitle: 'በእንጅባራ ከተማ ውስጥ የሚፈልጉትን ቤት ያግኙ',
    findPropertyDesc: 'በእንጅባራ ከተማ ቀበሌዎች እና ዩኒቨርሲቲ አካባቢ የተረጋገጡ የመኖሪያ ቤቶች እና የንግድ ቦታዎች።',
    filters: 'ማጣሪያዎች',
    clear: 'አጽዳ',
    areaKebele: 'አካባቢ / ቀበሌ',
    allAreas: 'ሁሉም አካባቢዎች',
    propertyType: 'የቤት አይነት',
    allTypes: 'ሁሉም አይነቶች',
    residentialHouse: 'የመኖሪያ ቤት',
    commercialShop: 'የንግድ ሱቅ',
    hotelShiro: 'ለሆቴል እና ለምግብ (ሽሮ) ቤት',
    electronicsPhoto: 'ለኤሌክትሮኒክስ እና ፎቶ ቤት',
    pharmacyClinic: 'ለፋርማሲ እና ክሊኒክ',
    otherCommercial: 'ሌሎች የንግድና የአገልግሎት ቦታዎች',
    applyFilters: 'ማጣሪያዎችን ተግብር',
    mapView: 'በካርታ እይታ',
    priceRange: 'የዋጋ መጠን',
    roomsLabel: 'ክፍሎች',
    propertyCategories: 'የቤት ምድቦች',
    categoriesInInjibara: 'በእንጅባራ ከተማ ያሉ የንብረት ምድቦች',
    categoriesDesc: 'በፍላጎትዎ መሰረት የተደራጁ የተለያዩ የቤት አማራጮችን ያስሱ። ከመኖሪያ እስከ ንግድ ቦታዎች ሁሉንም ያገኛሉ።',
    interactiveMap: 'ቀጥታ ካርታ',
    mapDesc: 'በካርታው ላይ ያሉትን የቤት አማራጮች ያስሱ።',
    aboutHeroTag: 'ስለ እኛ',
    aboutHeroTitle: 'ለእንጅባራ ከተማ የተሰራ',
    aboutHeroSubtitle: 'በቀላሉ፣ በፍጥነት፣ እና በታማኝነት ቤቶችን የሚያገናኝ መድረክ።',
    exploreHouses: 'ቤቶችን ያስሱ',
    browseCategories: 'ምድቦችን ያስሱ',
    ourMission: 'ተልዕኳችን',
    missionText: 'በእንጅባራ እና አካባቢዋ ለሚገኙ ነዋሪዎች እና አዲስ መጪዎች፣ ተመጣጣኝ እና የተረጋገጡ የቤት አማራጮችን በማቅረብ የቤት ፍለጋን ማቅለል ነው።',
    verifiedListings: 'የተረጋገጡ ቤቶች',
    ourVision: 'ራዕያችን',
    visionText: 'የመኖሪያ እና የንግድ ቦታ ፍለጋን በማዘመን ሁሉም ሰው የሚፈልገውን ቤት በቀላሉ የሚያገኝበትን አስተማማኝ ስርዓት መገንባት ነው።',
    nationwideCoverage: 'አስተማማኝ ሽፋን',
    coreValues: 'ዋና እሴቶቻችን',
    valuesText: 'ታማኝነት፣ ግልጽነት እና ለተጠቃሚዎቻችን ቅድሚያ መስጠት የስራችን መሰረት ናቸው።',
    zeroFees: 'ቀላል እና ፈጣን',
    tailoredExp: 'ለእርስዎ የተዘጋጀ',
    builtForBoth: 'ለአከራይም ለተከራይም የተሰራ',
    streamlineDesc: 'አሰራራችን ለሁለቱም ወገኖች ቀላል እና ግልጽ እንዲሆን ታስቦ የተዘጋጀ ነው።',
    forTenants: 'ለተከራዮች',
    forLandlords: 'ለአከራዮች',
    kebeleFiltering: 'በቀበሌ መፈለግ',
    kebeleFilteringDesc: 'በሚፈልጉት ቀበሌ እና አካባቢ ብቻ ቤቶችን ይፈልጉ።',
    oneClickRequest: 'ቀላል ጥያቄ',
    oneClickRequestDesc: 'በአንድ ጠቅታ ለሚፈልጉት ቤት ጥያቄ ይላኩ።',
    liveUpdates: 'ፈጣን መረጃ',
    liveUpdatesDesc: 'አዳዲስ ቤቶች ሲወጡ ፈጣን መረጃ ያግኙ።',
    freeListings: 'ነጻ ምዝገባ',
    freeListingsDesc: 'ቤቶን ያለ ምንም ክፍያ በነጻ ያስመዝግቡ።',
    reviewApplicants: 'ጠያቂዎችን መገምገም',
    reviewApplicantsDesc: 'የቤቶን ፈላጊዎች ዝርዝር በቀላሉ ይገምግሙ።',
    dashboardMgmt: 'የዳሽቦርድ አስተዳደር',
    dashboardMgmtDesc: 'ሁሉንም መረጃዎን በአንድ ቦታ ያስተዳድሩ።',
    ourFootprint: 'አሻራችን',
    footprintDesc: 'በእንጅባራ ከተማ የቤት ኪራይ ገበያ ላይ ያመጣነው ለውጥ።',
    propertiesListed: 'የተመዘገቡ ቤቶች',
    majorCities: 'ቀበሌዎች',
    verifiedUsers: 'ተጠቃሚዎች',
    tenantSatisfaction: 'የደንበኞች እርካታ',
    faqTitle: 'ተዘውትረው የሚጠየቁ ጥያቄዎች (FAQ)',
    gotQuestions: 'ጥያቄዎች አሉዎት?',
    navigatingDesc: 'ስለ መድረካችን አጠቃቀም እና ሌሎች ጉዳዮች የሚነሱ ጥያቄዎች እና መልሶቻቸው።',
    readyToFind: 'ቀጣዩን ቤቶን ለማግኘት ዝግጁ ነዎት?',
    browseDesc: 'አሁን ያስሱ እና የሚፈልጉትን ቤት በቀላሉ ያግኙ።',
    browseNow: 'አሁኑኑ ያስሱ',
    customerExperience: 'የደንበኞች ተሞክሮ',
    testimonialTitle: 'ተጠቃሚዎቻችን ምን ይላሉ?',
    testimonialSubtitle: 'ከአከራዮች እና ተከራዮች የተሰጡ አስተያየቶች።',
    // Nav
    home: 'መነሻ',
    houses: 'ቤቶች',
    categories: 'መደቦች',
    about: 'ስለ እኛ',
    contact: 'ግንኙነት',
    messages: 'መልእክቶች',
    dashboard: 'ዳሽቦርድ',
    signIn: 'ግቡ',
    register: 'ተመዝገቡ',
    signOut: 'ውጡ',
    today: 'ዛሬ',
    loginToMessage: 'ተግባብተዉ ለመልእክት ይግቡ',
    loginToMessageDesc: 'የደላላና የተከራይ መልእክቶችን ለመመልከት እና ለመላክ እባክዎ አስቀድመው ወደ መለያዎ ይግቡ።',
    messagesSubtitle: `በ${CITY_CONFIG.cityNameAm} ከተማ ቀበሌዎች ያሉ ቤቶችን፣ ኪራዮችንና ዋጋዎችን በተመለከተ በቀጥታ ይነጋገሩ።`,
    brandSub: CITY_CONFIG.brandSubAm,
    amharaHouse: CITY_CONFIG.brandNameAm,
    langName: 'አማርኛ',
    switchLang: 'English',
    // Home / General
    welcomeTitle: CITY_CONFIG.heroTitleAm,
    searchPlaceholder: CITY_CONFIG.searchPlaceholderAm,
    searchBtn: 'ቤቶችን ፈልግ',
    requestRental: 'ቤት ተከራይ',
    availableHouses: 'የሚከራዩ ቤቶች',
    viewDetails: 'ዝርዝር ይመልከቱ',
    contactOwner: 'አከራዩን ያግኙ',
    featuredHouses: 'የተመረጡ ቤቶች',
    allCategories: 'ሁሉም መደቦች',
    price: 'ዋጋ',
    perMonth: 'ብር/በወር',
    bedrooms: 'መተኛ ክፍሎች',
    bathrooms: 'መታጠቢያዎች',
    bathsLabel: 'መታጠቢያዎች',
    area: 'ስፋት',
    sqm: 'ካሬ ሜትር',
    sqmFull: 'ካሬ ሜትር',
    typeLabel: 'ዓይነት',
    location: 'አድራሻ',
    saveProperty: 'ምኞት ላይ አስቀምጥ',
    saved: 'ተቀምጧል',
    available: 'ክፍት (የሚከራይ)',
    rented: 'ተከራይቷል',
    vipFeatured: 'ቪአይፒ የተመረጠ',
    chatLandlord: 'አከራይን ያውሩ',
    contactBroker: 'ደላላ ያግኙ',
    requestBtn: 'ቤት ተከራይ',
    showingProperties: `በ${CITY_CONFIG.cityNameAm} ከተማ የሚከራዩ ቤቶች ዝርዝር`,
    sortBy: 'አደራደር',
    featuredFirst: 'የተመረጡት መጀመሪያ',
    newestFirst: 'አዲስ የተመዘገቡ',
    priceLowHigh: 'ዋጋ፡ ከዝቅተኛ ወደ ከፍተኛ',
    priceHighLow: 'ዋጋ፡ ከከፍተኛ ወደ ዝቅተኛ',
    noPropertiesFound: 'ምንም ዓይነት ቤት አልተገኘም',
    noPropertiesMsg: `በ${CITY_CONFIG.cityNameAm} ከተማ ከገለጹት መስፈርት ጋር የሚጣጣም ምንም አይነት ቤት አልተገኘም።`,
    clearFilters: 'ሁሉንም ፊልተሮች አጥፋ',
    // Dashboard / User Portal
    properties: 'የእኔ ቤቶች',
    favs: 'ምኞት ዝርዝር',
    rentRequests: 'የኪራይ ጥያቄዎች',
    seekingAds: 'የፈላጊ ማስታወቂያዎች',
    savedAlerts: 'የተቀመጡ ማሳወቂያዎች',
    payments: 'ክፍያዎች',
    profile: 'መገለጫ',
    analytics: 'ትንተና',
    allUsers: 'ሁሉም ተጠቃሚዎች',
    activeListings: 'የሚከራዩ ቤቶች',
    rentedListings: 'የተከራዩ ቤቶች',
    postedVsRented: 'የተመዘገቡ እና የተከራዩ ቤቶች ወርሃዊ ለውጥ',
    performanceDashboard: 'የንብረት ትንተና ዳሽቦርድ',
    // Forms
    addProperty: 'አዲስ ቤት መዝግብ',
    editProperty: 'ቤቱን አድስ',
    titleLabel: 'ርዕስ',
    descLabel: 'ዝርዝር መግለጫ',
    rooms: 'ክፍሎች',
    baths: 'መታጠቢያዎች',
    sqmLabel: 'ካሬ ሜትር',
    region: 'ክልል',
    city: 'ከተማ',
    subCity: 'ክፍለ ከተማ',
    address: 'አድራሻ',
    saveChanges: 'አስቀምጥ',
    cancel: 'ተው',
    // Alerts
    minPrice: 'ዝቅተኛ ዋጋ',
    maxPrice: 'ከፍተኛ ዋጋ',
    locationKeyword: 'የአድራሻ ቃል',
    minRooms: 'ቢያንስ ክፍሎች',
    notificationEmail: 'ማሳወቂያ ኢሜይል',
    createAlert: 'ማሳወቂያ ፍጠር',
    testAlert: 'ሙከራ ኢሜይል ላክ',
    emailLogs: 'የተላኩ ማሳወቂያዎች',
    preview: 'ይመልከቱ',
    // Categories / Types
    residential: 'የመኖሪያ ቤት',
    villa: 'ቪላ',
    apartment: 'አፓርታማ',
    commercial: 'ለንግድ ቤት',
    condo: 'ኮንዶሚኒየም',
    studio: 'ስቱዲዮ',
    office: 'ቢሮ',
    warehouse: 'መጋዘን',
    land: 'መሬት / ቦታ',
    // About Page
    // Rental Request Modal
    bookingRequest: 'የቤት መከራያ ጥያቄ',
    reviews: 'ደረጃ እና አስተያየቶች',
    moveInDate: 'የመግቢያ ቀን',
    noteToOwner: 'ለባለቤቱ ማስታወሻ',
    sendRequest: 'የኪራይ ጥያቄ ላክ',
    propertyRented: 'ቤት ተከራይቷል',
    alreadyRentedMsg: 'ይህ ቤት አስቀድሞ ተከራይቷል! ለአንድ ቤት ከአንድ በላይ ተከራይ ማከራየት አይቻልም።',
    bookingSuccess: 'የኪራይ ጥያቄ ተልኳል!',
    bookingSuccessMsg: 'የመከራያ ጥያቄዎ በተካሳ ሁኔታ ለቤት ባለቤቱ ደርሷል።',
    digitalContract: 'ዲጂታል የቤት ኪራይ ውል ስምምነት PDF',
    prepareContract: 'ህጋዊ ውል ማዘጋጀት ይፈልጋሉ?',
    // Navbar Extras
    dateTime: 'ቀን እና ሰዓት',
    currentTime: 'አሁን ያለው ሰዓት',
    notifs: 'ማሳወቂያዎች',
    markAllRead: 'ሁሉንም ተነበዋል በል',
    noNotifs: 'ምንም ማሳወቂያ የለም',
    watchVideo: 'ቪዲዮ እይ',
    contactUs: 'እኛን ለማግኘት',
    getInTouch: 'ይገናኙን',
    contactDesc: 'በእንጅባራ ከተማ ቤት መከራየት ወይም ማከራየት ይፈልጋሉ? ደውለውልን ወይም መልእክት ይላኩልን።',
    contactDetails: 'አድራሻ እና ስልክ',
    contactDetailsDesc: 'በእንጅባራ ከተማ ቤቶችንና የንግድ ሱቆችን በፍጥነት ለማግኘት ያነጋግሩን።',
    phone: 'ስልክ ቁጥር',
    email: 'ኢሜይል',
    officeLocation: 'ቢሮ አድራሻ',
    officeLocationValue: 'እንጅባራ፣ ቀበሌ 01 (መሃል ከተማ ከንግድ ባንክ አጠገብ)፣ አዊ ዞን',
    sendMessage: 'መልእክት ይላኩ',
    yourName: 'ሙሉ ስም',
    enterYourName: 'እባክዎን ስምዎን ያስገቡ',
    yourEmail: 'ኢሜይል',
    subject: 'ርዕስ',
    propertySubject: 'የሚፈልጉት የቤት አይነት',
    message: 'መልእክት',
    writeMessage: 'ስለሚፈልጉት ቤት ወይም የንግድ ቦታ ይጻፉልን...',
    messageSentSuccess: 'መልእክትዎ ደርሶናል! በቅርቡ እንደውላለን።',
    addPropertyTitle: 'አዲስ ቤት ያስመዝግቡ',
    addPropertySubtitle: 'ዝርዝር መረጃዎችን በመሙላት ቤቱን ለተከራዮች እና ለገዢዎች ያስተውውቁ።',
    ownerSelection: 'የቤት ባለቤት ምርጫ',
    ownerSelectPlaceholder: '-- ባለቤቱን ይምረጡ --',
    propertyTitle: 'የቤት ርዕስ',
    propertyTitlePlaceholder: 'ምሳሌ፡ እንጅባራ ቀበሌ 01 2 ክፍል የመኖሪያ ቤት',
    regionArea: 'ክልል / አካባቢ',
    cityZone: 'ዞን / ከተማ',
    subCityWereda: 'ወረዳ / ክፍለ ከተማ',
    rentPriceLabel: 'የወር ኪራይ በብር',
    pricePlaceholder: 'ምሳሌ፡ 8500',
    roomsCount: 'የክፍል ብዛት',
    bathroomsCount: 'የመታጠቢያ ቤት ብዛት',
    squareMeterLabel: 'የቤት ስፋት በካሬ',
    addressLabel: 'ልዩ አድራሻ',
    addressPlaceholder: 'ምሳሌ፡ ከAgni ሆስፒታል ጀርባ',
    propertyImages: 'የቤት ፎቶዎች',
    propertyImagesDesc: 'ቢያንስ 3-5 ጥራት ያላቸው ፎቶዎችን ቢጨምሩ ተመራጭ ነው፤ ተከራዮች በደንብ እንዲያዩት ይረዳል።',
    propertyVideo: 'የቪዲዮ ገለጻ',
    propertyVideoDesc: 'አጭር የቪዲዮ Walkthrough በመጨመር ቤቱን በደንብ ያስተውውቁ።',
    submitListing: 'ቤቱን መዝግብ',
    createAccount: 'መለያ ይፍጠሩ',
    joinNetwork: 'የኢትዮጵያን ቀዳሚ የሪል ስቴት እና የቤት ኪራይ ኔትወርክ ይቀላቀሉ',
    fullName: 'ሙሉ ስም',
    emailAddress: 'ኢሜይል',
    phoneNumber: 'ስልክ ቁጥር',
    password: 'የይለፍ ቃል',
    confirmPassword: 'የይለፍ ቃል አረጋግጥ',
    iamA: 'እኔ...',
    houseSeeker: 'ቤት ፈላጊ (ተከራይ)',
    propertyOwner: 'የቤት ባለቤት (አከራይ)',
    registerBtn: 'አሁኑኑ ተመዝገብ',
    alreadyHaveAccount: 'አስቀድመው መለያ አለዎት?',
    loginLink: 'ይግቡ',
    signInTitle: 'እንኳን ደህና መጡ',
    signInSubtitle: 'መልእክቶችዎን፣ የጠበቋቸውን ቤቶች ወይም ያስመዘገቡትን ቤት ለማየት ይግቡ።',
    dontHaveAccount: 'መለያ የለዎትም?',
    registerLink: 'ተመዝገብ',
    loggingIn: 'በመግባት ላይ...',
    online: 'ኦንላይን',
    cityTown: 'ከተማ',
    selectCity: 'ከተማ ይምረጡ',
    kebeleOptional: 'ቀበሌ / ክፍለ ከተማ (አማራጭ)',
    creatingAccount: 'በመመዝገብ ላይ...',
    completeRegistration: 'ምዝገባውን ጨርስ',
    virtualTour: '360° የቪዲዮ ጉብኝት',
    virtualTourSubtitle: 'የቤቱን ውስጣዊና ውጫዊ ገፅታዎች በቪዲዮ ይመልከቱ',
    openLink: 'በአዲስ ታብ ክፈት',
    dateListed: 'የተለጠፈበት ቀን',
    inAppDirectMessaging: 'ቀጥታ መልእክት መለዋወጫ',
    exploreProperties: 'ቤቶችን ይፈልጉ',
    searchMessages: 'መልእክቶችን ወይም ሰዎችን ይፈልጉ...',
    contactLandlords: 'አዲስ ከአከራይ/ደላላ ጋር ያውሩ',
    sendMessageAction: 'መልእክት ላክ',
    startChatting: 'ከአከራዩ ጋር በቀጥታ ይነጋገሩ!',
    onlineCaps: 'ኦንላይን',
    onlineStatus: 'ኦንላይን ይገኛሉ',
    offlineStatus: 'ከሲስተሙ ውጭ',
    viewDetailsAction: 'ቤቱን ይመልከቱ',
    testingModeMsg: 'ይህ የእርስዎ የቤት ማስታወቂያ/አካውንት ነው (Testing Mode). ከታች የሙከራ መልእክት መላክ ይችላሉ!',
    beginningOfConversation: 'ይህ የቀጥታ ንግግሮ መጀመሪያ ነው።',
    askQuestions: 'ስለ ቤቱ ኪራይ፣ ዋጋ ወይም ቤቱን ስለማየት ጥያቄዎችን ይጠይቁ!',
    sentStatus: 'ተልኳል',
    writeMessageTo: 'መልእክት ይጻፉ ለ',
    sendAction: 'ላክ',
    selectConversation: 'ውይይት ይምረጡ',
    chooseToStartChatting: 'በቀጥታ ለመነጋገር ከበስተግራ በኩል አከራይ ወይም ተከራይ ይምረጡ።',
    featuredPropertiesText: 'የተመረጡ ቤቶች',
    loadingProperties: 'ያሉትን ቤቶች እያመጣ ነው...',
    exploreAvailable: 'ያሉትን የ',
    propertiesInInjibara: 'ቤቶች በእንጅባራ እና አካባቢዋ ይመልከቱ',
    viewAll: 'ሁሉንም እይ',
    calendarInfo: 'በኢትዮጵያ ካላንደር (EC) ወይም በግሪጎሪያን (GC) ይምረጡ።',
    liveTenantRequests: 'ቀጥታ የተከራዮች ፍላጎት',
    tenantSeekingTitle: 'የቤት ፈላጊዎች ፍላጎት ዝርዝር',
    tenantSeekingSubtitle: 'አከራዮች እና ደላላዎች፡ እምቅ ተከራዮች ምን እንደሚፈልጉ እዚህ ይመልከቱ እና በቀጥታ ያግኙዋቸው!',
    postSeekingRequest: 'የቤት ፈላጊ ፍላጎት ያስመዝግቡ',
    postSeekingRequestDesc: 'የሚፈልጉትን የቤት አይነት፣ በጀት እና አድራሻ በመሙላት ያስመዝግቡ።',
    noSeekingRequests: 'ምንም ፍላጎት እስካሁን አልተመዘገበም',
    noSeekingRequestsDesc: 'የሚፈልጉትን ቤት መስፈርቶች ያስመዝግቡና የቤት ባለቤቶች እንዲያገኙዎት ያድርጉ!',
    postFirstRequest: 'የመጀመሪያውን ፍላጎት ያስመዝግቡ',
    seeker: 'ቤት ፈላጊ (ተከራይ)',
    postedOn: 'የተለጠፈው በ',
    callPhone: 'ደውል',
    call: 'ደውል',
    houseType: 'የቤት ዓይነት',
    notSpecified: 'አልተገለጸም',
    budget: 'በጀት',
    contactLandlordSystem: 'ባለቤቱን በሲስተሙ ያውሩት',
    selectFromList: 'ከዝርዝሩ ውስጥ ይምረጡ',
    typeCustom: 'በጽሁፍ ይጻፉ',
    customHouseTypePlaceholder: 'የሚፈልጉትን የቤት አይነት ይጻፉ (ምሳሌ፡ ሱቅ፣ መጋዘን...)',
    maxBudget: 'ከፍተኛ በጀት (በብር)',
    budgetPlaceholder: 'ምሳሌ፡ 15000',
    seekingRequestSuccessMsg: 'የቤት ፍላጎት ጥያቄዎ በተሳካ ሁኔታ ተመዝግቦ በዋናው ገጽ ላይ እንዲታይ ተደርጓል።',
    viewSlider: 'ወደ ዝርዝሩ ተመለስ',
    verifiedPlatform: 'የተረጋገጠ ሲስተም',
    verifiedProperty: 'የተረጋገጠ ቤት',
    directLandlordContact: 'ከባለቤቱ ጋር ቀጥታ ግንኙነት',
    shareProperty: 'ቤቱን ያጋሩ',
    copied: 'ኮፒ ተደርጓል!',
    videoPlaybackError: 'የእርስዎ ብሮውዘር ቪዲዮ ማጫወት አይችልም።',
    defaultLocation: 'እንጅባራ, ኢትዮጵያ',
    landlordLabel: 'አከራይ',
    monthlyRent: 'የወር ኪራይ',
    directMessaging: 'ቀጥታ መልዕክት መለዋወጫ',
    smartPropertyMap: 'ዘመናዊ ካርታ',
    houseRentalBooking: 'የቤት ኪራይ ምዝገባ',
    allRightsReserved: 'መብቱ በህግ የተጠበቀ ነው።',
    footerDescription: 'በእንጅባራ ከተማ የተረጋገጡ የመኖሪያ ቤቶችን እና የንግድ ቦታዎችን ያግኙ።',
    ethiopia: 'ኢትዮጵያ',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'am';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'am' : 'en'));
  };

  const t = (key, fallback) => {
    return translations[language]?.[key] || fallback || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
